#!/bin/sh
runnable() {
  local test_file="$1"
  local test_helper="$(dirname "$0")/helper"
  local test_directory="/tmp/rcm-test.$$"
  local src_directory="$(dirname "$0")/.."

  [ -f "$test_helper" ] || test_helper=/dev/null

  cat <<EOF
ret=0

export SRC_DIR="$src_directory"
export TEST_DIR="$test_directory"

fail() {
  printf "  failure: %s\\n" "\$*"
  ret=1
}

pending() {
  printf "  pending: %s\\n" "\$*"
  exit
}

$(cat "$test_helper")

mkdir -p "\$TEST_DIR"
cd "\$TEST_DIR"

$(cat "$test_file")

cd - >/dev/null
rm -r "\$TEST_DIR"
exit \$ret
EOF
}

cases=0
errors=0

for test_case in "$(dirname "$0")"/cases/*; do
  cases=$(($cases+1))

  printf "Test case: %s...\n" "$test_case"

  if ! runnable "$test_case" | sh; then
    errors=$(($errors+1))
  fi
done

printf "\nFailures: %s/%s\n" "$errors" "$cases"

exit $errors
